// //  class DataHandler {
// //    constructor(){
// // //     this."movie"Data = [
// // //       // { "Date": "2023-12-15", "Screen": 1, Time: "13:00", "Movie": "Inception", "Premier" : true, "Price": 500, "Duration": 1,"imgSource" : "https://m.media-amazon.com/images/M/MV5BYzFjMThiMGItOWRlMC00MDI4LThmOGUtYTNlZGZiYWI1YjMyXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg","Discription":"In a fairy tale, Princess Moanna, whose father is the king of the underworld, visits the human world, where the sunlight blinds her and erases her memory. She becomes mortal and eventually dies. The king believes that eventually, her spirit will return to the underworld, so he builds labyrinths, which act as portals, around the world in preparation for her return." },
// // //       // { "Date": "2023-12-15", "Screen": 1, Time: "14:30", "Movie": "Inception", "Premier" : true, "Price": 500, "Duration": 1,"imgSource" : "https://m.media-amazon.com/images/M/MV5BYzFjMThiMGItOWRlMC00MDI4LThmOGUtYTNlZGZiYWI1YjMyXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg","Discription":"In a fairy tale, Princess Moanna, whose father is the king of the underworld, visits the human world, where the sunlight blinds her and erases her memory. She becomes mortal and eventually dies. The king believes that eventually, her spirit will return to the underworld, so he builds labyrinths, which act as portals, around the world in preparation for her return." },
// // //       // { "Date": "2023-12-15", "Screen": 1, Time: "16:00", "Movie": "Inception", "Premier" : true, "Price": 500, "Duration": 1,"imgSource" : "https://m.media-amazon.com/images/M/MV5BYzFjMThiMGItOWRlMC00MDI4LThmOGUtYTNlZGZiYWI1YjMyXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg","Discription":"In a fairy tale, Princess Moanna, whose father is the king of the underworld, visits the human world, where the sunlight blinds her and erases her memory. She becomes mortal and eventually dies. The king believes that eventually, her spirit will return to the underworld, so he builds labyrinths, which act as portals, around the world in preparation for her return." },
// // //       // { "Date": "2023-12-15", "Screen": 1, Time: "17:30", "Movie": "Inception", "Premier" : true, "Price": 500, "Duration": 1,"imgSource" : "https://m.media-amazon.com/images/M/MV5BYzFjMThiMGItOWRlMC00MDI4LThmOGUtYTNlZGZiYWI1YjMyXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg","Discription":"In a fairy tale, Princess Moanna, whose father is the king of the underworld, visits the human world, where the sunlight blinds her and erases her memory. She becomes mortal and eventually dies. The king believes that eventually, her spirit will return to the underworld, so he builds labyrinths, which act as portals, around the world in preparation for her return." },
// // //       // { "Date": "2023-12-15", "Screen": 1, Time: "19:00", "Movie": "Inception", "Premier" : true, "Price": 500, "Duration": 1,"imgSource" : "https://m.media-amazon.com/images/M/MV5BYzFjMThiMGItOWRlMC00MDI4LThmOGUtYTNlZGZiYWI1YjMyXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg","Discription":"In a fairy tale, Princess Moanna, whose father is the king of the underworld, visits the human world, where the sunlight blinds her and erases her memory. She becomes mortal and eventually dies. The king believes that eventually, her spirit will return to the underworld, so he builds labyrinths, which act as portals, around the world in preparation for her return." },

// // //       // { "Date": "2023-12-15", "Screen": 2, Time: "13:00", "Movie": "The Dark Knight", "Price": 150, "Duration": 1,"imgSource" : "https://s3.amazonaws.com/static.rogerebert.com/uploads/movie/movie_poster/the-matrix-1999/large_gynBNzwyaHKtXqlEKKLioNkjKgN.jpg","Discription":"At an abandoned hotel, a police squad corners Trinity, who overpowers them with superhuman abilities. She flees, pursued by the police and a groupof suited Agents capable of similar superhuman feats. She answers a ringing public telephone and vanishes." },
// // //       // { "Date": "2023-12-15", "Screen": 2, Time: "14:30", "Movie": "The Dark Knight", "Price": 150, "Duration": 1,"imgSource" : "https://s3.amazonaws.com/static.rogerebert.com/uploads/movie/movie_poster/the-matrix-1999/large_gynBNzwyaHKtXqlEKKLioNkjKgN.jpg","Discription":"At an abandoned hotel, a police squad corners Trinity, who overpowers them with superhuman abilities. She flees, pursued by the police and a groupof suited Agents capable of similar superhuman feats. She answers a ringing public telephone and vanishes." },
// // //       // { "Date": "2023-12-15", "Screen": 2, Time: "16:00", "Movie": "The Dark Knight", "Price": 150, "Duration": 1,"imgSource" : "https://s3.amazonaws.com/static.rogerebert.com/uploads/movie/movie_poster/the-matrix-1999/large_gynBNzwyaHKtXqlEKKLioNkjKgN.jpg","Discription":"At an abandoned hotel, a police squad corners Trinity, who overpowers them with superhuman abilities. She flees, pursued by the police and a groupof suited Agents capable of similar superhuman feats. She answers a ringing public telephone and vanishes." },
// // //       // { "Date": "2023-12-15", "Screen": 2, Time: "17:30", "Movie": "The Dark Knight", "Price": 150, "Duration": 1,"imgSource" : "https://s3.amazonaws.com/static.rogerebert.com/uploads/movie/movie_poster/the-matrix-1999/large_gynBNzwyaHKtXqlEKKLioNkjKgN.jpg","Discription":"At an abandoned hotel, a police squad corners Trinity, who overpowers them with superhuman abilities. She flees, pursued by the police and a groupof suited Agents capable of similar superhuman feats. She answers a ringing public telephone and vanishes." },
// // //       // { "Date": "2023-12-15", "Screen": 2, Time: "19:00", "Movie": "The Dark Knight", "Price": 150, "Duration": 1,"imgSource" : "https://s3.amazonaws.com/static.rogerebert.com/uploads/movie/movie_poster/the-matrix-1999/large_gynBNzwyaHKtXqlEKKLioNkjKgN.jpg","Discription":"At an abandoned hotel, a police squad corners Trinity, who overpowers them with superhuman abilities. She flees, pursued by the police and a groupof suited Agents capable of similar superhuman feats. She answers a ringing public telephone and vanishes." },

// // //       // { "Date": "2023-12-15", "Screen": 3, Time: "13:00", "Movie": "Forrest Gump", "Price": 150, "Duration": 1,"imgSource" : "https://play-lh.googleusercontent.com/ToGy2Cue0epHBdeRkq3dntz8on4ogI1UlKLGqMvgCptTwmpMWVkIxojwVUuvIjrMIFz2UiNjW73xcuofHQ=w240-h480-rw","Discription":"As a boy in 1956, Forrest has an IQ of 75 and is fitted with leg braces to correct a curved spine. He lives in Greenbow, Alabama, with his mother, who runs a boarding house and encourages him to live beyond his disabilities. Among their temporary tenants is a young Elvis Presley, who plays the guitar for Forrest and is inspired to incorporate the boy's jerky leg and hip movements into his performances. " },
// // //       // { "Date": "2023-12-15", "Screen": 3, Time: "16:00", "Movie": "Forrest Gump", "Price": 150, "Duration": 1,"imgSource" : "https://play-lh.googleusercontent.com/ToGy2Cue0epHBdeRkq3dntz8on4ogI1UlKLGqMvgCptTwmpMWVkIxojwVUuvIjrMIFz2UiNjW73xcuofHQ=w240-h480-rw","Discription":"As a boy in 1956, Forrest has an IQ of 75 and is fitted with leg braces to correct a curved spine. He lives in Greenbow, Alabama, with his mother, who runs a boarding house and encourages him to live beyond his disabilities. Among their temporary tenants is a young Elvis Presley, who plays the guitar for Forrest and is inspired to incorporate the boy's jerky leg and hip movements into his performances. " },
// // //       // { "Date": "2023-12-15", "Screen": 3, Time: "17:30", "Movie": "Forrest Gump", "Price": 150, "Duration": 1,"imgSource" : "https://play-lh.googleusercontent.com/ToGy2Cue0epHBdeRkq3dntz8on4ogI1UlKLGqMvgCptTwmpMWVkIxojwVUuvIjrMIFz2UiNjW73xcuofHQ=w240-h480-rw","Discription":"As a boy in 1956, Forrest has an IQ of 75 and is fitted with leg braces to correct a curved spine. He lives in Greenbow, Alabama, with his mother, who runs a boarding house and encourages him to live beyond his disabilities. Among their temporary tenants is a young Elvis Presley, who plays the guitar for Forrest and is inspired to incorporate the boy's jerky leg and hip movements into his performances. " },
// // //       // { "Date": "2023-12-15", "Screen": 3, Time: "19:00", "Movie": "Forrest Gump", "Price": 150, "Duration": 1,"imgSource" : "https://play-lh.googleusercontent.com/ToGy2Cue0epHBdeRkq3dntz8on4ogI1UlKLGqMvgCptTwmpMWVkIxojwVUuvIjrMIFz2UiNjW73xcuofHQ=w240-h480-rw","Discription":"As a boy in 1956, Forrest has an IQ of 75 and is fitted with leg braces to correct a curved spine. He lives in Greenbow, Alabama, with his mother, who runs a boarding house and encourages him to live beyond his disabilities. Among their temporary tenants is a young Elvis Presley, who plays the guitar for Forrest and is inspired to incorporate the boy's jerky leg and hip movements into his performances. " },
// // //       // { "Date": "2023-12-15", "Screen": 3, Time: "13:00", "Movie": "Forrest Gump", "Price": 150, "Duration": 1,"imgSource" : "https://play-lh.googleusercontent.com/ToGy2Cue0epHBdeRkq3dntz8on4ogI1UlKLGqMvgCptTwmpMWVkIxojwVUuvIjrMIFz2UiNjW73xcuofHQ=w240-h480-rw","Discription":"As a boy in 1956, Forrest has an IQ of 75 and is fitted with leg braces to correct a curved spine. He lives in Greenbow, Alabama, with his mother, who runs a boarding house and encourages him to live beyond his disabilities. Among their temporary tenants is a young Elvis Presley, who plays the guitar for Forrest and is inspired to incorporate the boy's jerky leg and hip movements into his performances. " },
// // //       // { "Date": "2023-12-15", "Screen": 3, Time: "14:30", "Movie": "Forrest Gump", "Price": 150, "Duration": 1,"imgSource" : "https://play-lh.googleusercontent.com/ToGy2Cue0epHBdeRkq3dntz8on4ogI1UlKLGqMvgCptTwmpMWVkIxojwVUuvIjrMIFz2UiNjW73xcuofHQ=w240-h480-rw","Discription":"As a boy in 1956, Forrest has an IQ of 75 and is fitted with leg braces to correct a curved spine. He lives in Greenbow, Alabama, with his mother, who runs a boarding house and encourages him to live beyond his disabilities. Among their temporary tenants is a young Elvis Presley, who plays the guitar for Forrest and is inspired to incorporate the boy's jerky leg and hip movements into his performances. " },
// // //       // { "Date": "2023-12-15", "Screen": 3, Time: "16:00", "Movie": "Forrest Gump", "Price": 150, "Duration": 1,"imgSource" : "https://play-lh.googleusercontent.com/ToGy2Cue0epHBdeRkq3dntz8on4ogI1UlKLGqMvgCptTwmpMWVkIxojwVUuvIjrMIFz2UiNjW73xcuofHQ=w240-h480-rw","Discription":"As a boy in 1956, Forrest has an IQ of 75 and is fitted with leg braces to correct a curved spine. He lives in Greenbow, Alabama, with his mother, who runs a boarding house and encourages him to live beyond his disabilities. Among their temporary tenants is a young Elvis Presley, who plays the guitar for Forrest and is inspired to incorporate the boy's jerky leg and hip movements into his performances. " },
// // //       // { "Date": "2023-12-15", "Screen": 3, Time: "17:30", "Movie": "Forrest Gump", "Price": 150, "Duration": 1,"imgSource" : "https://play-lh.googleusercontent.com/ToGy2Cue0epHBdeRkq3dntz8on4ogI1UlKLGqMvgCptTwmpMWVkIxojwVUuvIjrMIFz2UiNjW73xcuofHQ=w240-h480-rw","Discription":"As a boy in 1956, Forrest has an IQ of 75 and is fitted with leg braces to correct a curved spine. He lives in Greenbow, Alabama, with his mother, who runs a boarding house and encourages him to live beyond his disabilities. Among their temporary tenants is a young Elvis Presley, who plays the guitar for Forrest and is inspired to incorporate the boy's jerky leg and hip movements into his performances. " },
// // //       // { "Date": "2023-12-15", "Screen": 3, Time: "19:00", "Movie": "Forrest Gump", "Price": 150, "Duration": 1,"imgSource" : "https://play-lh.googleusercontent.com/ToGy2Cue0epHBdeRkq3dntz8on4ogI1UlKLGqMvgCptTwmpMWVkIxojwVUuvIjrMIFz2UiNjW73xcuofHQ=w240-h480-rw","Discription":"As a boy in 1956, Forrest has an IQ of 75 and is fitted with leg braces to correct a curved spine. He lives in Greenbow, Alabama, with his mother, who runs a boarding house and encourages him to live beyond his disabilities. Among their temporary tenants is a young Elvis Presley, who plays the guitar for Forrest and is inspired to incorporate the boy's jerky leg and hip movements into his performances. " },

// // //       // { "Date": "2023-12-15", "Screen": 4, Time: "13:00", "Movie": "Schindler's List", "Price": 150, "Duration": 1,"imgSource" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6298/6298052_sa.jpg","Discription":"In Kraków during World War II, the Nazis force local Polish Jews into the overcrowded Kraków Ghetto. Oskar Schindler, a German Nazi Party member from Czechoslovakia, arrives in the city, hoping to make his fortune. He bribes Wehrmacht (German armed forces) and SS officials, acquiring a factory to produce enamelware. Schindler hires Itzhak Stern, a Jewish official with contacts among black marketeers and the Jewish business community; he handles administration and helps Schindler arrange financing." },
// // //       // { "Date": "2023-12-15", "Screen": 4, Time: "14:30", "Movie": "Schindler's List", "Price": 150, "Duration": 1,"imgSource" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6298/6298052_sa.jpg","Discription":"In Kraków during World War II, the Nazis force local Polish Jews into the overcrowded Kraków Ghetto. Oskar Schindler, a German Nazi Party member from Czechoslovakia, arrives in the city, hoping to make his fortune. He bribes Wehrmacht (German armed forces) and SS officials, acquiring a factory to produce enamelware. Schindler hires Itzhak Stern, a Jewish official with contacts among black marketeers and the Jewish business community; he handles administration and helps Schindler arrange financing." },
// // //       // { "Date": "2023-12-15", "Screen": 4, Time: "16:00", "Movie": "Schindler's List", "Price": 150, "Duration": 1,"imgSource" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6298/6298052_sa.jpg","Discription":"In Kraków during World War II, the Nazis force local Polish Jews into the overcrowded Kraków Ghetto. Oskar Schindler, a German Nazi Party member from Czechoslovakia, arrives in the city, hoping to make his fortune. He bribes Wehrmacht (German armed forces) and SS officials, acquiring a factory to produce enamelware. Schindler hires Itzhak Stern, a Jewish official with contacts among black marketeers and the Jewish business community; he handles administration and helps Schindler arrange financing." },
// // //       // { "Date": "2023-12-15", "Screen": 4, Time: "17:30", "Movie": "Schindler's List", "Price": 150, "Duration": 1,"imgSource" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6298/6298052_sa.jpg","Discription":"In Kraków during World War II, the Nazis force local Polish Jews into the overcrowded Kraków Ghetto. Oskar Schindler, a German Nazi Party member from Czechoslovakia, arrives in the city, hoping to make his fortune. He bribes Wehrmacht (German armed forces) and SS officials, acquiring a factory to produce enamelware. Schindler hires Itzhak Stern, a Jewish official with contacts among black marketeers and the Jewish business community; he handles administration and helps Schindler arrange financing." },
// // //       // { "Date": "2023-12-15", "Screen": 4, Time: "19:00", "Movie": "Schindler's List", "Price": 150, "Duration": 1,"imgSource" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6298/6298052_sa.jpg","Discription":"In Kraków during World War II, the Nazis force local Polish Jews into the overcrowded Kraków Ghetto. Oskar Schindler, a German Nazi Party member from Czechoslovakia, arrives in the city, hoping to make his fortune. He bribes Wehrmacht (German armed forces) and SS officials, acquiring a factory to produce enamelware. Schindler hires Itzhak Stern, a Jewish official with contacts among black marketeers and the Jewish business community; he handles administration and helps Schindler arrange financing." },

// // //       // { "Date": "2023-12-15", "Screen": 5, Time: "13:00", "Movie": "Whiplash", "Price": 150, "Duration": 1,"imgSource" : "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p10488558_p_v12_ai.jpg","Discription":"Andrew Neiman is a first-year student and jazz drummer at the prestigious Shaffer Conservatory in New York City, hoping one day to leave a legacy like that of his childhood idol, jazz drummer Buddy Rich. Terence Fletcher, the conductor of the Shaffer Conservatory Studio Band, recruits him to play in the Studio ensemble as an alternate for core drummer Carl Tanner. " },
// // //       // { "Date": "2023-12-15", "Screen": 5, Time: "14:30", "Movie": "Whiplash", "Price": 150, "Duration": 1,"imgSource" : "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p10488558_p_v12_ai.jpg","Discription":"Andrew Neiman is a first-year student and jazz drummer at the prestigious Shaffer Conservatory in New York City, hoping one day to leave a legacy like that of his childhood idol, jazz drummer Buddy Rich. Terence Fletcher, the conductor of the Shaffer Conservatory Studio Band, recruits him to play in the Studio ensemble as an alternate for core drummer Carl Tanner. " },
// // //       // { "Date": "2023-12-15", "Screen": 5, Time: "16:00", "Movie": "Whiplash", "Price": 150, "Duration": 1,"imgSource" : "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p10488558_p_v12_ai.jpg","Discription":"Andrew Neiman is a first-year student and jazz drummer at the prestigious Shaffer Conservatory in New York City, hoping one day to leave a legacy like that of his childhood idol, jazz drummer Buddy Rich. Terence Fletcher, the conductor of the Shaffer Conservatory Studio Band, recruits him to play in the Studio ensemble as an alternate for core drummer Carl Tanner. " },
// // //       // { "Date": "2023-12-15", "Screen": 5, Time: "17:30", "Movie": "Whiplash", "Price": 150, "Duration": 1,"imgSource" : "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p10488558_p_v12_ai.jpg","Discription":"Andrew Neiman is a first-year student and jazz drummer at the prestigious Shaffer Conservatory in New York City, hoping one day to leave a legacy like that of his childhood idol, jazz drummer Buddy Rich. Terence Fletcher, the conductor of the Shaffer Conservatory Studio Band, recruits him to play in the Studio ensemble as an alternate for core drummer Carl Tanner. " },
// // //       // { "Date": "2023-12-15", "Screen": 5, Time: "19:00", "Movie": "Whiplash", "Price": 150, "Duration": 1,"imgSource" : "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p10488558_p_v12_ai.jpg","Discription":"Andrew Neiman is a first-year student and jazz drummer at the prestigious Shaffer Conservatory in New York City, hoping one day to leave a legacy like that of his childhood idol, jazz drummer Buddy Rich. Terence Fletcher, the conductor of the Shaffer Conservatory Studio Band, recruits him to play in the Studio ensemble as an alternate for core drummer Carl Tanner. " },



// // //       // { "Date": "2023-12-16", "Screen": 1, Time: "13:00", "Movie": "Inception", "Premier" : true, "Price": 500, "Duration": 1,"imgSource" : "https://m.media-amazon.com/images/M/MV5BYzFjMThiMGItOWRlMC00MDI4LThmOGUtYTNlZGZiYWI1YjMyXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg","Discription":"In a fairy tale, Princess Moanna, whose father is the king of the underworld, visits the human world, where the sunlight blinds her and erases her memory. She becomes mortal and eventually dies. The king believes that eventually, her spirit will return to the underworld, so he builds labyrinths, which act as portals, around the world in preparation for her return." },
// // //       // { "Date": "2023-12-16", "Screen": 1, Time: "14:30", "Movie": "Inception", "Premier" : true, "Price": 500, "Duration": 1,"imgSource" : "https://m.media-amazon.com/images/M/MV5BYzFjMThiMGItOWRlMC00MDI4LThmOGUtYTNlZGZiYWI1YjMyXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg","Discription":"In a fairy tale, Princess Moanna, whose father is the king of the underworld, visits the human world, where the sunlight blinds her and erases her memory. She becomes mortal and eventually dies. The king believes that eventually, her spirit will return to the underworld, so he builds labyrinths, which act as portals, around the world in preparation for her return." },
// // //       // { "Date": "2023-12-16", "Screen": 1, Time: "16:00", "Movie": "Inception", "Premier" : true, "Price": 500, "Duration": 1,"imgSource" : "https://m.media-amazon.com/images/M/MV5BYzFjMThiMGItOWRlMC00MDI4LThmOGUtYTNlZGZiYWI1YjMyXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg","Discription":"In a fairy tale, Princess Moanna, whose father is the king of the underworld, visits the human world, where the sunlight blinds her and erases her memory. She becomes mortal and eventually dies. The king believes that eventually, her spirit will return to the underworld, so he builds labyrinths, which act as portals, around the world in preparation for her return." },
// // //       // { "Date": "2023-12-16", "Screen": 1, Time: "17:30", "Movie": "Inception", "Premier" : true, "Price": 500, "Duration": 1,"imgSource" : "https://m.media-amazon.com/images/M/MV5BYzFjMThiMGItOWRlMC00MDI4LThmOGUtYTNlZGZiYWI1YjMyXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg","Discription":"In a fairy tale, Princess Moanna, whose father is the king of the underworld, visits the human world, where the sunlight blinds her and erases her memory. She becomes mortal and eventually dies. The king believes that eventually, her spirit will return to the underworld, so he builds labyrinths, which act as portals, around the world in preparation for her return." },
// // //       // { "Date": "2023-12-16", "Screen": 1, Time: "19:00", "Movie": "Inception", "Premier" : true, "Price": 500, "Duration": 1,"imgSource" : "https://m.media-amazon.com/images/M/MV5BYzFjMThiMGItOWRlMC00MDI4LThmOGUtYTNlZGZiYWI1YjMyXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg","Discription":"In a fairy tale, Princess Moanna, whose father is the king of the underworld, visits the human world, where the sunlight blinds her and erases her memory. She becomes mortal and eventually dies. The king believes that eventually, her spirit will return to the underworld, so he builds labyrinths, which act as portals, around the world in preparation for her return." },

// // //       // { "Date": "2023-12-16", "Screen": 2, Time: "13:00", "Movie": "The Dark Knight", "Price": 150, "Duration": 1,"imgSource" : "https://s3.amazonaws.com/static.rogerebert.com/uploads/movie/movie_poster/the-matrix-1999/large_gynBNzwyaHKtXqlEKKLioNkjKgN.jpg","Discription":"At an abandoned hotel, a police squad corners Trinity, who overpowers them with superhuman abilities. She flees, pursued by the police and a groupof suited Agents capable of similar superhuman feats. She answers a ringing public telephone and vanishes." },
// // //       // { "Date": "2023-12-16", "Screen": 2, Time: "14:30", "Movie": "The Dark Knight", "Price": 150, "Duration": 1,"imgSource" : "https://s3.amazonaws.com/static.rogerebert.com/uploads/movie/movie_poster/the-matrix-1999/large_gynBNzwyaHKtXqlEKKLioNkjKgN.jpg","Discription":"At an abandoned hotel, a police squad corners Trinity, who overpowers them with superhuman abilities. She flees, pursued by the police and a groupof suited Agents capable of similar superhuman feats. She answers a ringing public telephone and vanishes." },
// // //       // { "Date": "2023-12-16", "Screen": 2, Time: "16:00", "Movie": "The Dark Knight", "Price": 150, "Duration": 1,"imgSource" : "https://s3.amazonaws.com/static.rogerebert.com/uploads/movie/movie_poster/the-matrix-1999/large_gynBNzwyaHKtXqlEKKLioNkjKgN.jpg","Discription":"At an abandoned hotel, a police squad corners Trinity, who overpowers them with superhuman abilities. She flees, pursued by the police and a groupof suited Agents capable of similar superhuman feats. She answers a ringing public telephone and vanishes." },
// // //       // { "Date": "2023-12-16", "Screen": 2, Time: "17:30", "Movie": "The Dark Knight", "Price": 150, "Duration": 1,"imgSource" : "https://s3.amazonaws.com/static.rogerebert.com/uploads/movie/movie_poster/the-matrix-1999/large_gynBNzwyaHKtXqlEKKLioNkjKgN.jpg","Discription":"At an abandoned hotel, a police squad corners Trinity, who overpowers them with superhuman abilities. She flees, pursued by the police and a groupof suited Agents capable of similar superhuman feats. She answers a ringing public telephone and vanishes." },
// // //       // { "Date": "2023-12-16", "Screen": 2, Time: "19:00", "Movie": "The Dark Knight", "Price": 150, "Duration": 1,"imgSource" : "https://s3.amazonaws.com/static.rogerebert.com/uploads/movie/movie_poster/the-matrix-1999/large_gynBNzwyaHKtXqlEKKLioNkjKgN.jpg","Discription":"At an abandoned hotel, a police squad corners Trinity, who overpowers them with superhuman abilities. She flees, pursued by the police and a groupof suited Agents capable of similar superhuman feats. She answers a ringing public telephone and vanishes." },

// // //       // { "Date": "2023-12-16", "Screen": 3, Time: "13:00", "Movie": "Forrest Gump", "Price": 150, "Duration": 1,"imgSource" : "https://play-lh.googleusercontent.com/ToGy2Cue0epHBdeRkq3dntz8on4ogI1UlKLGqMvgCptTwmpMWVkIxojwVUuvIjrMIFz2UiNjW73xcuofHQ=w240-h480-rw","Discription":"As a boy in 1956, Forrest has an IQ of 75 and is fitted with leg braces to correct a curved spine. He lives in Greenbow, Alabama, with his mother, who runs a boarding house and encourages him to live beyond his disabilities. Among their temporary tenants is a young Elvis Presley, who plays the guitar for Forrest and is inspired to incorporate the boy's jerky leg and hip movements into his performances. " },
// // //       // { "Date": "2023-12-16", "Screen": 3, Time: "14:30", "Movie": "Forrest Gump", "Price": 150, "Duration": 1,"imgSource" : "https://play-lh.googleusercontent.com/ToGy2Cue0epHBdeRkq3dntz8on4ogI1UlKLGqMvgCptTwmpMWVkIxojwVUuvIjrMIFz2UiNjW73xcuofHQ=w240-h480-rw","Discription":"As a boy in 1956, Forrest has an IQ of 75 and is fitted with leg braces to correct a curved spine. He lives in Greenbow, Alabama, with his mother, who runs a boarding house and encourages him to live beyond his disabilities. Among their temporary tenants is a young Elvis Presley, who plays the guitar for Forrest and is inspired to incorporate the boy's jerky leg and hip movements into his performances. " },
// // //       // { "Date": "2023-12-16", "Screen": 3, Time: "16:00", "Movie": "Forrest Gump", "Price": 150, "Duration": 1,"imgSource" : "https://play-lh.googleusercontent.com/ToGy2Cue0epHBdeRkq3dntz8on4ogI1UlKLGqMvgCptTwmpMWVkIxojwVUuvIjrMIFz2UiNjW73xcuofHQ=w240-h480-rw","Discription":"As a boy in 1956, Forrest has an IQ of 75 and is fitted with leg braces to correct a curved spine. He lives in Greenbow, Alabama, with his mother, who runs a boarding house and encourages him to live beyond his disabilities. Among their temporary tenants is a young Elvis Presley, who plays the guitar for Forrest and is inspired to incorporate the boy's jerky leg and hip movements into his performances. " },
// // //       // { "Date": "2023-12-16", "Screen": 3, Time: "17:30", "Movie": "Forrest Gump", "Price": 150, "Duration": 1,"imgSource" : "https://play-lh.googleusercontent.com/ToGy2Cue0epHBdeRkq3dntz8on4ogI1UlKLGqMvgCptTwmpMWVkIxojwVUuvIjrMIFz2UiNjW73xcuofHQ=w240-h480-rw","Discription":"As a boy in 1956, Forrest has an IQ of 75 and is fitted with leg braces to correct a curved spine. He lives in Greenbow, Alabama, with his mother, who runs a boarding house and encourages him to live beyond his disabilities. Among their temporary tenants is a young Elvis Presley, who plays the guitar for Forrest and is inspired to incorporate the boy's jerky leg and hip movements into his performances. " },
// // //       // { "Date": "2023-12-16", "Screen": 3, Time: "19:00", "Movie": "Forrest Gump", "Price": 150, "Duration": 1,"imgSource" : "https://play-lh.googleusercontent.com/ToGy2Cue0epHBdeRkq3dntz8on4ogI1UlKLGqMvgCptTwmpMWVkIxojwVUuvIjrMIFz2UiNjW73xcuofHQ=w240-h480-rw","Discription":"As a boy in 1956, Forrest has an IQ of 75 and is fitted with leg braces to correct a curved spine. He lives in Greenbow, Alabama, with his mother, who runs a boarding house and encourages him to live beyond his disabilities. Among their temporary tenants is a young Elvis Presley, who plays the guitar for Forrest and is inspired to incorporate the boy's jerky leg and hip movements into his performances. " },
// // //       // { "Date": "2023-12-16", "Screen": 3, Time: "13:00", "Movie": "Forrest Gump", "Price": 150, "Duration": 1,"imgSource" : "https://play-lh.googleusercontent.com/ToGy2Cue0epHBdeRkq3dntz8on4ogI1UlKLGqMvgCptTwmpMWVkIxojwVUuvIjrMIFz2UiNjW73xcuofHQ=w240-h480-rw","Discription":"As a boy in 1956, Forrest has an IQ of 75 and is fitted with leg braces to correct a curved spine. He lives in Greenbow, Alabama, with his mother, who runs a boarding house and encourages him to live beyond his disabilities. Among their temporary tenants is a young Elvis Presley, who plays the guitar for Forrest and is inspired to incorporate the boy's jerky leg and hip movements into his performances. " },
// // //       // { "Date": "2023-12-16", "Screen": 3, Time: "14:30", "Movie": "Forrest Gump", "Price": 150, "Duration": 1,"imgSource" : "https://play-lh.googleusercontent.com/ToGy2Cue0epHBdeRkq3dntz8on4ogI1UlKLGqMvgCptTwmpMWVkIxojwVUuvIjrMIFz2UiNjW73xcuofHQ=w240-h480-rw","Discription":"As a boy in 1956, Forrest has an IQ of 75 and is fitted with leg braces to correct a curved spine. He lives in Greenbow, Alabama, with his mother, who runs a boarding house and encourages him to live beyond his disabilities. Among their temporary tenants is a young Elvis Presley, who plays the guitar for Forrest and is inspired to incorporate the boy's jerky leg and hip movements into his performances. " },
// // //       // { "Date": "2023-12-16", "Screen": 3, Time: "16:00", "Movie": "Forrest Gump", "Price": 150, "Duration": 1,"imgSource" : "https://play-lh.googleusercontent.com/ToGy2Cue0epHBdeRkq3dntz8on4ogI1UlKLGqMvgCptTwmpMWVkIxojwVUuvIjrMIFz2UiNjW73xcuofHQ=w240-h480-rw","Discription":"As a boy in 1956, Forrest has an IQ of 75 and is fitted with leg braces to correct a curved spine. He lives in Greenbow, Alabama, with his mother, who runs a boarding house and encourages him to live beyond his disabilities. Among their temporary tenants is a young Elvis Presley, who plays the guitar for Forrest and is inspired to incorporate the boy's jerky leg and hip movements into his performances. " },
// // //       // { "Date": "2023-12-16", "Screen": 3, Time: "17:30", "Movie": "Forrest Gump", "Price": 150, "Duration": 1,"imgSource" : "https://play-lh.googleusercontent.com/ToGy2Cue0epHBdeRkq3dntz8on4ogI1UlKLGqMvgCptTwmpMWVkIxojwVUuvIjrMIFz2UiNjW73xcuofHQ=w240-h480-rw","Discription":"As a boy in 1956, Forrest has an IQ of 75 and is fitted with leg braces to correct a curved spine. He lives in Greenbow, Alabama, with his mother, who runs a boarding house and encourages him to live beyond his disabilities. Among their temporary tenants is a young Elvis Presley, who plays the guitar for Forrest and is inspired to incorporate the boy's jerky leg and hip movements into his performances. " },
// // //       // { "Date": "2023-12-16", "Screen": 3, Time: "19:00", "Movie": "Forrest Gump", "Price": 150, "Duration": 1,"imgSource" : "https://play-lh.googleusercontent.com/ToGy2Cue0epHBdeRkq3dntz8on4ogI1UlKLGqMvgCptTwmpMWVkIxojwVUuvIjrMIFz2UiNjW73xcuofHQ=w240-h480-rw","Discription":"As a boy in 1956, Forrest has an IQ of 75 and is fitted with leg braces to correct a curved spine. He lives in Greenbow, Alabama, with his mother, who runs a boarding house and encourages him to live beyond his disabilities. Among their temporary tenants is a young Elvis Presley, who plays the guitar for Forrest and is inspired to incorporate the boy's jerky leg and hip movements into his performances. " },

// // //       // { "Date": "2023-12-16", "Screen": 4, Time: "13:00", "Movie": "Schindler's List", "Price": 150, "Duration": 1,"imgSource" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6298/6298052_sa.jpg","Discription":"In Kraków during World War II, the Nazis force local Polish Jews into the overcrowded Kraków Ghetto. Oskar Schindler, a German Nazi Party member from Czechoslovakia, arrives in the city, hoping to make his fortune. He bribes Wehrmacht (German armed forces) and SS officials, acquiring a factory to produce enamelware. Schindler hires Itzhak Stern, a Jewish official with contacts among black marketeers and the Jewish business community; he handles administration and helps Schindler arrange financing." },
// // //       // { "Date": "2023-12-16", "Screen": 4, Time: "14:30", "Movie": "Schindler's List", "Price": 150, "Duration": 1,"imgSource" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6298/6298052_sa.jpg","Discription":"In Kraków during World War II, the Nazis force local Polish Jews into the overcrowded Kraków Ghetto. Oskar Schindler, a German Nazi Party member from Czechoslovakia, arrives in the city, hoping to make his fortune. He bribes Wehrmacht (German armed forces) and SS officials, acquiring a factory to produce enamelware. Schindler hires Itzhak Stern, a Jewish official with contacts among black marketeers and the Jewish business community; he handles administration and helps Schindler arrange financing." },
// // //       // { "Date": "2023-12-16", "Screen": 4, Time: "16:00", "Movie": "Schindler's List", "Price": 150, "Duration": 1,"imgSource" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6298/6298052_sa.jpg","Discription":"In Kraków during World War II, the Nazis force local Polish Jews into the overcrowded Kraków Ghetto. Oskar Schindler, a German Nazi Party member from Czechoslovakia, arrives in the city, hoping to make his fortune. He bribes Wehrmacht (German armed forces) and SS officials, acquiring a factory to produce enamelware. Schindler hires Itzhak Stern, a Jewish official with contacts among black marketeers and the Jewish business community; he handles administration and helps Schindler arrange financing." },
// // //       // { "Date": "2023-12-16", "Screen": 4, Time: "17:30", "Movie": "Schindler's List", "Price": 150, "Duration": 1,"imgSource" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6298/6298052_sa.jpg","Discription":"In Kraków during World War II, the Nazis force local Polish Jews into the overcrowded Kraków Ghetto. Oskar Schindler, a German Nazi Party member from Czechoslovakia, arrives in the city, hoping to make his fortune. He bribes Wehrmacht (German armed forces) and SS officials, acquiring a factory to produce enamelware. Schindler hires Itzhak Stern, a Jewish official with contacts among black marketeers and the Jewish business community; he handles administration and helps Schindler arrange financing." },
// // //       // { "Date": "2023-12-16", "Screen": 4, Time: "19:00", "Movie": "Schindler's List", "Price": 150, "Duration": 1,"imgSource" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6298/6298052_sa.jpg","Discription":"In Kraków during World War II, the Nazis force local Polish Jews into the overcrowded Kraków Ghetto. Oskar Schindler, a German Nazi Party member from Czechoslovakia, arrives in the city, hoping to make his fortune. He bribes Wehrmacht (German armed forces) and SS officials, acquiring a factory to produce enamelware. Schindler hires Itzhak Stern, a Jewish official with contacts among black marketeers and the Jewish business community; he handles administration and helps Schindler arrange financing." },
      
// // //       // { "Date": "2023-12-16", "Screen": 5, Time: "13:00", "Movie": "Whiplash", "Price": 150, "Duration": 1,"imgSource" : "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p10488558_p_v12_ai.jpg","Discription":"Andrew Neiman is a first-year student and jazz drummer at the prestigious Shaffer Conservatory in New York City, hoping one day to leave a legacy like that of his childhood idol, jazz drummer Buddy Rich. Terence Fletcher, the conductor of the Shaffer Conservatory Studio Band, recruits him to play in the Studio ensemble as an alternate for core drummer Carl Tanner. " },
// // //       // { "Date": "2023-12-16", "Screen": 5, Time: "14:30", "Movie": "Whiplash", "Price": 150, "Duration": 1,"imgSource" : "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p10488558_p_v12_ai.jpg","Discription":"Andrew Neiman is a first-year student and jazz drummer at the prestigious Shaffer Conservatory in New York City, hoping one day to leave a legacy like that of his childhood idol, jazz drummer Buddy Rich. Terence Fletcher, the conductor of the Shaffer Conservatory Studio Band, recruits him to play in the Studio ensemble as an alternate for core drummer Carl Tanner. " },
// // //       // { "Date": "2023-12-16", "Screen": 5, Time: "16:00", "Movie": "Whiplash", "Price": 150, "Duration": 1,"imgSource" : "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p10488558_p_v12_ai.jpg","Discription":"Andrew Neiman is a first-year student and jazz drummer at the prestigious Shaffer Conservatory in New York City, hoping one day to leave a legacy like that of his childhood idol, jazz drummer Buddy Rich. Terence Fletcher, the conductor of the Shaffer Conservatory Studio Band, recruits him to play in the Studio ensemble as an alternate for core drummer Carl Tanner. " },
// // //       // { "Date": "2023-12-16", "Screen": 5, Time: "17:30", "Movie": "Whiplash", "Price": 150, "Duration": 1,"imgSource" : "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p10488558_p_v12_ai.jpg","Discription":"Andrew Neiman is a first-year student and jazz drummer at the prestigious Shaffer Conservatory in New York City, hoping one day to leave a legacy like that of his childhood idol, jazz drummer Buddy Rich. Terence Fletcher, the conductor of the Shaffer Conservatory Studio Band, recruits him to play in the Studio ensemble as an alternate for core drummer Carl Tanner. " },
// // //       // { "Date": "2023-12-16", "Screen": 5, Time: "19:00", "Movie": "Whiplash", "Price": 150, "Duration": 1,"imgSource" : "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p10488558_p_v12_ai.jpg","Discription":"Andrew Neiman is a first-year student and jazz drummer at the prestigious Shaffer Conservatory in New York City, hoping one day to leave a legacy like that of his childhood idol, jazz drummer Buddy Rich. Terence Fletcher, the conductor of the Shaffer Conservatory Studio Band, recruits him to play in the Studio ensemble as an alternate for core drummer Carl Tanner. " },

// // //       { ,"Discription":"" },
// // //       { ,"Discription":"" },
// // //       { ,"Discription":"" },
// // //       { ,"Discription":"" },
// // //       { ,"Discription":"" },
   
// // //       { ,"Discription":"" },
// // //       { ,"Discription":"" },
// // //       { ,"Discription":"" },
// // //       { ,"Discription":"" },
// // //       { ,"Discription":"" },
      
  
// // //       { ,"Discription":"" },
// // //       { ,"Discription":"" },
// // //       { ,"Discription":"" },
// // //       { ,"Discription":"" },
// // //       { ,"Discription":"" },
  
// // //       { ,"Discription":"" },
// // //       { ,"Discription":"" },
// // //       { ,"Discription":"" },
// // //       { ,"Discription":"" },
// // //       { ,"Discription":"" },
  
// // //       { ,"Discription":"" },
// // //       { ,"Discription":"" },
// // //       { ,"Discription":"" },
// // //       { ,"Discription":"" },
// // //       { ,"Discription":"" },
  
//       {  },
//       { "Date": "2023-12-16", "Screen": 1, "StartTime": "14:30", "EndTime": "15:30", "Movie": "Pans Labrinth", "Premier" : true, "Price": 500, "Duration": 1,"imgSource" : "https://m.media-amazon.com/images/M/MV5BYzFjMThiMGItOWRlMC00MDI4LThmOGUtYTNlZGZiYWI1YjMyXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg","Discription":"In a fairy tale, Princess Moanna, whose father is the king of the underworld, visits the human world, where the sunlight blinds her and erases her memory. She becomes mortal and eventually dies. The king believes that eventually, her spirit will return to the underworld, so he builds labyrinths, which act as portals, around the world in preparation for her return." },
//       { "Date": "2023-12-16", "Screen": 1, "StartTime": "16:00", "EndTime": "17:00", "Movie": "Pans Labrinth", "Premier" : true, "Price": 500, "Duration": 1,"imgSource" : "https://m.media-amazon.com/images/M/MV5BYzFjMThiMGItOWRlMC00MDI4LThmOGUtYTNlZGZiYWI1YjMyXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg","Discription":"In a fairy tale, Princess Moanna, whose father is the king of the underworld, visits the human world, where the sunlight blinds her and erases her memory. She becomes mortal and eventually dies. The king believes that eventually, her spirit will return to the underworld, so he builds labyrinths, which act as portals, around the world in preparation for her return." },
//       { "Date": "2023-12-16", "Screen": 1, "StartTime": "17:30", "EndTime": "18:30", "Movie": "Pans Labrinth", "Premier" : true, "Price": 500, "Duration": 1,"imgSource" : "https://m.media-amazon.com/images/M/MV5BYzFjMThiMGItOWRlMC00MDI4LThmOGUtYTNlZGZiYWI1YjMyXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg","Discription":"In a fairy tale, Princess Moanna, whose father is the king of the underworld, visits the human world, where the sunlight blinds her and erases her memory. She becomes mortal and eventually dies. The king believes that eventually, her spirit will return to the underworld, so he builds labyrinths, which act as portals, around the world in preparation for her return." },
//       { "Date": "2023-12-16", "Screen": 1, "StartTime": "19:00", "EndTime": "20:00", "Movie": "Pans Labrinth", "Premier" : true, "Price": 500, "Duration": 1,"imgSource" : "https://m.media-amazon.com/images/M/MV5BYzFjMThiMGItOWRlMC00MDI4LThmOGUtYTNlZGZiYWI1YjMyXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg","Discription":"In a fairy tale, Princess Moanna, whose father is the king of the underworld, visits the human world, where the sunlight blinds her and erases her memory. She becomes mortal and eventually dies. The king believes that eventually, her spirit will return to the underworld, so he builds labyrinths, which act as portals, around the world in preparation for her return." },
  
//       { "Date": "2023-12-16", "Screen": 2, "StartTime": "13:00", "EndTime": "14:00", "Movie": "The Matrix", "Price": 150, "Duration": 1,"imgSource" : "https://s3.amazonaws.com/static.rogerebert.com/uploads/movie/movie_poster/the-matrix-1999/large_gynBNzwyaHKtXqlEKKLioNkjKgN.jpg","Discription":"At an abandoned hotel, a police squad corners Trinity, who overpowers them with superhuman abilities. She flees, pursued by the police and a groupof suited Agents capable of similar superhuman feats. She answers a ringing public telephone and vanishes." },
//       { "Date": "2023-12-16", "Screen": 2, "StartTime": "14:30", "EndTime": "15:30", "Movie": "The Matrix", "Price": 150, "Duration": 1,"imgSource" : "https://s3.amazonaws.com/static.rogerebert.com/uploads/movie/movie_poster/the-matrix-1999/large_gynBNzwyaHKtXqlEKKLioNkjKgN.jpg","Discription":"At an abandoned hotel, a police squad corners Trinity, who overpowers them with superhuman abilities. She flees, pursued by the police and a groupof suited Agents capable of similar superhuman feats. She answers a ringing public telephone and vanishes." },
//       { "Date": "2023-12-16", "Screen": 2, "StartTime": "16:00", "EndTime": "17:00", "Movie": "The Matrix", "Price": 150, "Duration": 1,"imgSource" : "https://s3.amazonaws.com/static.rogerebert.com/uploads/movie/movie_poster/the-matrix-1999/large_gynBNzwyaHKtXqlEKKLioNkjKgN.jpg","Discription":"At an abandoned hotel, a police squad corners Trinity, who overpowers them with superhuman abilities. She flees, pursued by the police and a groupof suited Agents capable of similar superhuman feats. She answers a ringing public telephone and vanishes." },
//       { "Date": "2023-12-16", "Screen": 2, "StartTime": "17:30", "EndTime": "18:30", "Movie": "The Matrix", "Price": 150, "Duration": 1,"imgSource" : "https://s3.amazonaws.com/static.rogerebert.com/uploads/movie/movie_poster/the-matrix-1999/large_gynBNzwyaHKtXqlEKKLioNkjKgN.jpg","Discription":"At an abandoned hotel, a police squad corners Trinity, who overpowers them with superhuman abilities. She flees, pursued by the police and a groupof suited Agents capable of similar superhuman feats. She answers a ringing public telephone and vanishes." },
//       { "Date": "2023-12-16", "Screen": 2, "StartTime": "19:00", "EndTime": "20:00", "Movie": "The Matrix", "Price": 150, "Duration": 1,"imgSource" : "https://s3.amazonaws.com/static.rogerebert.com/uploads/movie/movie_poster/the-matrix-1999/large_gynBNzwyaHKtXqlEKKLioNkjKgN.jpg","Discription":"At an abandoned hotel, a police squad corners Trinity, who overpowers them with superhuman abilities. She flees, pursued by the police and a groupof suited Agents capable of similar superhuman feats. She answers a ringing public telephone and vanishes." },
  
//       { "Date": "2023-12-16", "Screen": 3, "StartTime": "13:00", "EndTime": "14:00", "Movie": "Forrest Gump", "Price": 150, "Duration": 1,"imgSource" : "https://play-lh.googleusercontent.com/ToGy2Cue0epHBdeRkq3dntz8on4ogI1UlKLGqMvgCptTwmpMWVkIxojwVUuvIjrMIFz2UiNjW73xcuofHQ=w240-h480-rw","Discription":"As a boy in 1956, Forrest has an IQ of 75 and is fitted with leg braces to correct a curved spine. He lives in Greenbow, Alabama, with his mother, who runs a boarding house and encourages him to live beyond his disabilities. Among their temporary tenants is a young Elvis Presley, who plays the guitar for Forrest and is inspired to incorporate the boy's jerky leg and hip movements into his performances. " },
//       { "Date": "2023-12-16", "Screen": 3, "StartTime": "14:30", "EndTime": "15:30", "Movie": "Forrest Gump", "Price": 150, "Duration": 1,"imgSource" : "https://play-lh.googleusercontent.com/ToGy2Cue0epHBdeRkq3dntz8on4ogI1UlKLGqMvgCptTwmpMWVkIxojwVUuvIjrMIFz2UiNjW73xcuofHQ=w240-h480-rw","Discription":"As a boy in 1956, Forrest has an IQ of 75 and is fitted with leg braces to correct a curved spine. He lives in Greenbow, Alabama, with his mother, who runs a boarding house and encourages him to live beyond his disabilities. Among their temporary tenants is a young Elvis Presley, who plays the guitar for Forrest and is inspired to incorporate the boy's jerky leg and hip movements into his performances. " },
//       { "Date": "2023-12-16", "Screen": 3, "StartTime": "16:00", "EndTime": "17:00", "Movie": "Forrest Gump", "Price": 150, "Duration": 1,"imgSource" : "https://play-lh.googleusercontent.com/ToGy2Cue0epHBdeRkq3dntz8on4ogI1UlKLGqMvgCptTwmpMWVkIxojwVUuvIjrMIFz2UiNjW73xcuofHQ=w240-h480-rw","Discription":"As a boy in 1956, Forrest has an IQ of 75 and is fitted with leg braces to correct a curved spine. He lives in Greenbow, Alabama, with his mother, who runs a boarding house and encourages him to live beyond his disabilities. Among their temporary tenants is a young Elvis Presley, who plays the guitar for Forrest and is inspired to incorporate the boy's jerky leg and hip movements into his performances. " },
//       { "Date": "2023-12-16", "Screen": 3, "StartTime": "17:30", "EndTime": "18:30", "Movie": "Forrest Gump", "Price": 150, "Duration": 1,"imgSource" : "https://play-lh.googleusercontent.com/ToGy2Cue0epHBdeRkq3dntz8on4ogI1UlKLGqMvgCptTwmpMWVkIxojwVUuvIjrMIFz2UiNjW73xcuofHQ=w240-h480-rw","Discription":"As a boy in 1956, Forrest has an IQ of 75 and is fitted with leg braces to correct a curved spine. He lives in Greenbow, Alabama, with his mother, who runs a boarding house and encourages him to live beyond his disabilities. Among their temporary tenants is a young Elvis Presley, who plays the guitar for Forrest and is inspired to incorporate the boy's jerky leg and hip movements into his performances. " },
//       { "Date": "2023-12-16", "Screen": 3, "StartTime": "19:00", "EndTime": "20:00", "Movie": "Forrest Gump", "Price": 150, "Duration": 1,"imgSource" : "https://play-lh.googleusercontent.com/ToGy2Cue0epHBdeRkq3dntz8on4ogI1UlKLGqMvgCptTwmpMWVkIxojwVUuvIjrMIFz2UiNjW73xcuofHQ=w240-h480-rw","Discription":"As a boy in 1956, Forrest has an IQ of 75 and is fitted with leg braces to correct a curved spine. He lives in Greenbow, Alabama, with his mother, who runs a boarding house and encourages him to live beyond his disabilities. Among their temporary tenants is a young Elvis Presley, who plays the guitar for Forrest and is inspired to incorporate the boy's jerky leg and hip movements into his performances. " },
  
//       { "Date": "2023-12-16", "Screen": 4, "StartTime": "13:00", "EndTime": "14:00", "Movie": "Schindler's List", "Price": 150, "Duration": 1,"imgSource" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6298/6298052_sa.jpg","Discription":"In Kraków during World War II, the Nazis force local Polish Jews into the overcrowded Kraków Ghetto. Oskar Schindler, a German Nazi Party member from Czechoslovakia, arrives in the city, hoping to make his fortune. He bribes Wehrmacht (German armed forces) and SS officials, acquiring a factory to produce enamelware. Schindler hires Itzhak Stern, a Jewish official with contacts among black marketeers and the Jewish business community; he handles administration and helps Schindler arrange financing." },
//       { "Date": "2023-12-16", "Screen": 4, "StartTime": "14:30", "EndTime": "15:30", "Movie": "Schindler's List", "Price": 150, "Duration": 1,"imgSource" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6298/6298052_sa.jpg","Discription":"In Kraków during World War II, the Nazis force local Polish Jews into the overcrowded Kraków Ghetto. Oskar Schindler, a German Nazi Party member from Czechoslovakia, arrives in the city, hoping to make his fortune. He bribes Wehrmacht (German armed forces) and SS officials, acquiring a factory to produce enamelware. Schindler hires Itzhak Stern, a Jewish official with contacts among black marketeers and the Jewish business community; he handles administration and helps Schindler arrange financing." },
//       { "Date": "2023-12-16", "Screen": 4, "StartTime": "16:00", "EndTime": "17:00", "Movie": "Schindler's List", "Price": 150, "Duration": 1,"imgSource" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6298/6298052_sa.jpg","Discription":"In Kraków during World War II, the Nazis force local Polish Jews into the overcrowded Kraków Ghetto. Oskar Schindler, a German Nazi Party member from Czechoslovakia, arrives in the city, hoping to make his fortune. He bribes Wehrmacht (German armed forces) and SS officials, acquiring a factory to produce enamelware. Schindler hires Itzhak Stern, a Jewish official with contacts among black marketeers and the Jewish business community; he handles administration and helps Schindler arrange financing." },
//       { "Date": "2023-12-16", "Screen": 4, "StartTime": "17:30", "EndTime": "18:30", "Movie": "Schindler's List", "Price": 150, "Duration": 1,"imgSource" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6298/6298052_sa.jpg","Discription":"In Kraków during World War II, the Nazis force local Polish Jews into the overcrowded Kraków Ghetto. Oskar Schindler, a German Nazi Party member from Czechoslovakia, arrives in the city, hoping to make his fortune. He bribes Wehrmacht (German armed forces) and SS officials, acquiring a factory to produce enamelware. Schindler hires Itzhak Stern, a Jewish official with contacts among black marketeers and the Jewish business community; he handles administration and helps Schindler arrange financing." },
//       { "Date": "2023-12-16", "Screen": 4, "StartTime": "19:00", "EndTime": "20:00", "Movie": "Schindler's List", "Price": 150, "Duration": 1,"imgSource" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6298/6298052_sa.jpg","Discription":"In Kraków during World War II, the Nazis force local Polish Jews into the overcrowded Kraków Ghetto. Oskar Schindler, a German Nazi Party member from Czechoslovakia, arrives in the city, hoping to make his fortune. He bribes Wehrmacht (German armed forces) and SS officials, acquiring a factory to produce enamelware. Schindler hires Itzhak Stern, a Jewish official with contacts among black marketeers and the Jewish business community; he handles administration and helps Schindler arrange financing." },
  
//       { "Date": "2023-12-16", "Screen": 5, "StartTime": "13:00", "EndTime": "14:00", "Movie": "Whiplash", "Price": 150, "Duration": 1,"imgSource" : "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p10488558_p_v12_ai.jpg","Discription":"Andrew Neiman is a first-year student and jazz drummer at the prestigious Shaffer Conservatory in New York City, hoping one day to leave a legacy like that of his childhood idol, jazz drummer Buddy Rich. Terence Fletcher, the conductor of the Shaffer Conservatory Studio Band, recruits him to play in the Studio ensemble as an alternate for core drummer Carl Tanner. " },
//       { "Date": "2023-12-16", "Screen": 5, "StartTime": "14:30", "EndTime": "15:30", "Movie": "Whiplash", "Price": 150, "Duration": 1,"imgSource" : "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p10488558_p_v12_ai.jpg","Discription":"Andrew Neiman is a first-year student and jazz drummer at the prestigious Shaffer Conservatory in New York City, hoping one day to leave a legacy like that of his childhood idol, jazz drummer Buddy Rich. Terence Fletcher, the conductor of the Shaffer Conservatory Studio Band, recruits him to play in the Studio ensemble as an alternate for core drummer Carl Tanner. " },
//       { "Date": "2023-12-16", "Screen": 5, "StartTime": "16:00", "EndTime": "17:00", "Movie": "Whiplash", "Price": 150, "Duration": 1,"imgSource" : "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p10488558_p_v12_ai.jpg","Discription":"Andrew Neiman is a first-year student and jazz drummer at the prestigious Shaffer Conservatory in New York City, hoping one day to leave a legacy like that of his childhood idol, jazz drummer Buddy Rich. Terence Fletcher, the conductor of the Shaffer Conservatory Studio Band, recruits him to play in the Studio ensemble as an alternate for core drummer Carl Tanner. " },
//       { "Date": "2023-12-16", "Screen": 5, "StartTime": "17:30", "EndTime": "18:30", "Movie": "Whiplash", "Price": 150, "Duration": 1,"imgSource" : "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p10488558_p_v12_ai.jpg","Discription":"Andrew Neiman is a first-year student and jazz drummer at the prestigious Shaffer Conservatory in New York City, hoping one day to leave a legacy like that of his childhood idol, jazz drummer Buddy Rich. Terence Fletcher, the conductor of the Shaffer Conservatory Studio Band, recruits him to play in the Studio ensemble as an alternate for core drummer Carl Tanner. " },
//       { "Date": "2023-12-16", "Screen": 5, "StartTime": "19:00", "EndTime": "20:00", "Movie": "Whiplash", "Price": 150, "Duration": 1,"imgSource" : "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p10488558_p_v12_ai.jpg","Discription":"Andrew Neiman is a first-year student and jazz drummer at the prestigious Shaffer Conservatory in New York City, hoping one day to leave a legacy like that of his childhood idol, jazz drummer Buddy Rich. Terence Fletcher, the conductor of the Shaffer Conservatory Studio Band, recruits him to play in the Studio ensemble as an alternate for core drummer Carl Tanner. " },
  

// // //     ];
// // //     this.filtered"Movie" = [];
// //    }
   




// // //    formatToCustom"Date"("date"String) {
// // //     const original"Date" = new "Date"("date"String);
// // //     const formatted"Date" = original"Date".toLocale"Date"String("en-US", {
// // //       weekday: "short",
// // //       month: "short",
// // //       day: "2-digit",
// // //       year: "numeric",
// // //     });
// // //     return formatted"Date";
// // //   }


   
// //    setfilterMoviesByDate(targetDate) {
// //     this.filtered"Movie"s = this."movie"Data.filter("movie" => this.formatToCustom"Date"("movie"."Date") === this.formatToCustom"Date"(target"Date"));
// //   }

// // //    getfilter"Movie"sBy"Date"() {
// // //     return this.filtered"Movie"s;
// // //   }

// // //   get"Movie"Data(){
// // //     return this."movie"Data;  
// // //   }
// //  }
// //  let dataHandler = new DataHandler();

// // // export default DataHandler;
// // // export { dataHandler };
